### GET all Expenses

GET http://localhost:8080/expense

### CREATE Expense

POST http://localhost:8080/expense/createExpense
Content-Type: application/json

{
  "amountOfExpense": "1.00",
  "expenseDate": "2022-05-09",
  "nameExpense": "sdgsdg",
  "categoriesId": "5",
  "userId":"1"

}

### GET ExpensebyUserId

GET http://localhost:8080/expense/user/2

### PUT update Expense

PUT http://localhost:8080/expense/30
Content-Type: application/json

{
  "amountOfExpense": "1.55",
  "expenseDate": "2023-05-21",
  "nameExpense": "karta kredytowa",
  "categoriesId": "1",
  "userId":"5"
}


### DELETE Expense
 DELETE http://localhost:8080/expense/2


### GET getTotalExpensesByUserId

GET http://localhost:8080/expense/total/2


### GET getTotalExpensesForAllUsers

GET  http://localhost:8080/expense/total


