### Get all Expenses

GET http://localhost:8080/expense

### Create Expense

POST http://localhost:8080/expense/createExpense
Content-Type: application/json

{
  "amountOfExpense": "400.45",
  "expenseDate": "2022-05-09",
  "nameExpense": "gdgdfg",
  "categoriesId": "2",
  "userId":"2"

}

### Get ExpensebyUserId

GET http://localhost:8080/expense/user/2

### Put update Expense

PUT http://localhost:8080/expense/30
Content-Type: application/json

{
  "amountOfExpense": "1.55",
  "expenseDate": "2023-05-21",
  "nameExpense": "karta kredytowa",
  "categoriesId": "5",
  "userId":"10"
}


### Delete Expense
 DELETE http://localhost:8080/expense/1


