### POST createExpensesCategory

POST http://localhost:8080/expenses-categories
Content-Type: application/json

{
  "name": "Dom"

}

### GET getExpensesCategoryById

GET http://localhost:8080/expenses-categories/1

### GET getAllExpensesCategories

GET http://localhost:8080/expenses-categories

### PUT updateCategory

PUT http://localhost:8080/expenses-categories/1
Content-Type: application/json

{
  "name": "cos"

}

### DELETE deleteExpensesCategoryById

DELETE http://localhost:8080/expenses-categories/9