### CREATE createIncome

POST http://localhost:8080/incomes/create
Content-Type: application/json

{
  "sourceOfIncome": "cos",
  "amountOfIncome": "4500",
  "receiptDate": "2023-06-01",
  "userId": "2"
}


### GET getAllIncomes

GET http://localhost:8080/incomes


### GET getIncomeByUserId

GET http://localhost:8080/incomes/user/2

### PUT updateIncome

PUT http://localhost:8080/incomes/1
Content-Type: application/json

{
  "sourceOfIncome": "wypłata",
  "amountOfIncome": "4500.00",
  "receiptDate": "2023-05-21",
  "userId": "1"
}

### DELETE deleteIncome
DELETE http://localhost:8080/incomes/1

### GET getTotalIncomesByUserId

GET http://localhost:8080/incomes/total/3