### Get all Users

GET http://localhost:8080/users/all

### Get user

GET http://localhost:8080/users/6

### Create Users

POST http://localhost:8080/users/add
Content-Type: application/json

{
  "userFirstName": "Jarek"
}

### Update User

PUT http://localhost:8080/users/5
Content-Type: application/json

{
  "userFirstName": "Jarek"
}

### Delete User

DELETE http://localhost:8080/users/3