### Get all Users

GET http://localhost:8080/users/all

### Get user

GET http://localhost:8080/users/8

### Create Users

POST http://localhost:8080/users/add
Content-Type: application/json

{
  "userFirstName": "a"
}

### Update User

PUT http://localhost:8080/users/10
Content-Type: application/json

{
  "userFirstName": " "
}

### Delete User

DELETE http://localhost:8080/users/14