### Get all Users

GET http://localhost:8080/users/all

### Get user

GET http://localhost:8080/users/1

### Create Users

POST http://localhost:8080/users/add
Content-Type: application/json

{
  "userFirstName": "Paulina"
}

### Update User

PUT http://localhost:8080/users/1
Content-Type: application/json

{
  "userFirstName": "Tomasz"
}

### Delete User

DELETE http://localhost:8080/users/1